services:
  db:
    container_name: user-task-db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  msa-user-mgmt:
    build:
      context: .
      dockerfile: msa-user-mgmt/Dockerfile
    container_name: msa-user-mgmt
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/user_db
    depends_on:
      db:
        condition: service_healthy
    network_mode: "service:db"

  msa-task-mgmt:
    build:
      context: .
      dockerfile: msa-task-mgmt/Dockerfile
    container_name: msa-task-mgmt
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/task_db
    depends_on:
      db:
        condition: service_healthy
    network_mode: "service:db"

  msa-dashboard:
    build:
      context: .
      dockerfile: msa-dashboard/Dockerfile
    container_name: msa-dashboard
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - msa-user-mgmt
      - msa-task-mgmt
    network_mode: "service:db"
